name: Wapiti Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pip
      run: |
        sudo apt-get install python3-dev
        sudo apt-get install libpcap-dev libpq-dev
        sudo apt-get install python-setuptools build-essential
        sudo apt-get install qtbase5-dev
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip

    - name: Install pip application
      run: |
        pip3 install --upgrade pip setuptools wheel ez_setup pyqt5
        pip3 install wapiti3

    - name: Run command
      run: |
        wapiti -u https://woovi.com/ -o report
    
    - name: Commit report folder
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add report
        git commit -m 'Add generated report'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
