name: Wapiti Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install pip
      run: |
        sudo apt-get install python3-dev
        sudo apt-get install libpcap-dev libpq-dev
        sudo apt-get install python-setuptools build-essential
        sudo apt-get install qtbase5-dev
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip

    - name: Install pip application
      run: |
        pip3 install --upgrade pip setuptools wheel ez_setup pyqt5
        pip3 install wapiti

    - name: Run command
      run: |
        wapiti -u https://woovi.com/ -o report
    
    - name: Commit report folder
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add report
        git commit -m 'Add generated report'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
